# 日志配置
logging:
  config: classpath:logback.xml

# 配置调度中心地址
xxl:
  job:
    executor:
      ip: 127.0.0.1
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: xxljob
    # 执行器和调度中心之间的通信令牌，如果没有配置，表示关闭了通信令牌的校验。
    # 在 xxl-job-admin 的配置文件中，有一个一模一样的配置项，两边都配置，就会进行校验。